Repository CESARBR/knot-gateway-webui, pull requests merged in 2020-07, with the labels that each got.

#76 devices: Fix modbus thing creation
  app/controllers/devices.js
  app/services/devices.js
Labels: bug, priority: medium

#79 Improve device modal with data item delete feature and fields requirements
  public/controllers.js
  public/styles/devices.less
  public/views/app.devices.html
Labels: enhancement, priority: medium

#78 devices: Use sensorId to fill data items
  app/services/devices.js
Labels: bug, priority: medium

#77 system: Add command to restart thingd
  Dockerfile
  app/controllers/devices.js
  app/services/system.js
  docker/thingd/start.sh
  docker/thingd/stop.sh
Labels: enhancement, priority: medium

#80 Improve device modal with api error message
  public/controllers.js
  public/views/app.devices.html
Labels: enhancement, priority: medium

#87 config: Update fog port and thingd device file
  config/default.json
  config/development.json
Labels: bug
